/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Digital mode: Disable digital mode. Digital input set to 0. */
#define PIO0_10_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Disable digital mode. Digital input set to 0. */
#define PIO0_15_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Select Digital mode: Disable digital mode. Digital input set to 0. */
#define PIO0_16_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Analog switch input control: Analog switch is closed. (enable) */
#define PIO0_23_ASW0_ENABLE 0x01u
/*!
 * @brief Select Digital mode: Disable digital mode. Digital input set to 0. */
#define PIO0_23_DIGIMODE_ANALOG 0x00u
/*!
 * @brief
 * Mode select (on-chip pull-up/pull-down resistor control): Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_23_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_29_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_30_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Analog switch input control: Analog switch is closed. (enable) */
#define PIO0_31_ASW0_ENABLE 0x01u
/*!
 * @brief Select Digital mode: Disable digital mode. Digital input set to 0. */
#define PIO0_31_DIGIMODE_ANALOG 0x00u
/*!
 * @brief
 * Mode select (on-chip pull-up/pull-down resistor control): Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_31_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Analog switch input control: Analog switch is closed. (enable) */
#define PIO1_5_ASW0_ENABLE 0x01u
/*!
 * @brief Select Digital mode: Disable digital mode. Digital input set to 0. */
#define PIO1_5_DIGIMODE_ANALOG 0x00u
/*!
 * @brief
 * Mode select (on-chip pull-up/pull-down resistor control): Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_5_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_8_DIGIMODE_DIGITAL 0x01u

/*! @name FC0_TXD_SCL_MISO_WS (number 95), JP49[3]/JP80[2]/P0_30-FC0_TXD_SCL_MISO_WS-TRACED1-CAN0_TD
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define INIT_PINS_DEBUG_UART_TX_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define INIT_PINS_DEBUG_UART_TX_SIGNAL TXD_SCL_MISO_WS
/*!
 * @brief Routed pin name */
#define INIT_PINS_DEBUG_UART_TX_PIN_NAME FC0_TXD_SCL_MISO_WS
/*!
 * @brief Label */
#define INIT_PINS_DEBUG_UART_TX_LABEL "JP49[3]/JP80[2]/P0_30-FC0_TXD_SCL_MISO_WS-TRACED1-CAN0_TD"
/*!
 * @brief Identifier */
#define INIT_PINS_DEBUG_UART_TX_NAME "DEBUG_UART_TX"
/*!
 * @brief Direction */
#define INIT_PINS_DEBUG_UART_TX_DIRECTION kPIN_MUX_DirectionInput
/*!
 * @brief PORT peripheral base pointer */
#define INIT_PINS_DEBUG_UART_TX_PORT 0
/*!
 * @brief PORT pin number */
#define INIT_PINS_DEBUG_UART_TX_PIN 30U
/*!
 * @brief PORT pin mask */
#define INIT_PINS_DEBUG_UART_TX_PIN_MASK (1U << 30U)
/* @} */
/*! @name FC0_RXD_SDA_MOSI_DATA (number 93), JP78[2]/P0_29-FC0_RXD_SDA_MOSI_DATA-TRACED2
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define INIT_PINS_DEBUG_UART_RX_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define INIT_PINS_DEBUG_UART_RX_SIGNAL RXD_SDA_MOSI_DATA
/*!
 * @brief Routed pin name */
#define INIT_PINS_DEBUG_UART_RX_PIN_NAME FC0_RXD_SDA_MOSI_DATA
/*!
 * @brief Label */
#define INIT_PINS_DEBUG_UART_RX_LABEL "JP78[2]/P0_29-FC0_RXD_SDA_MOSI_DATA-TRACED2"
/*!
 * @brief Identifier */
#define INIT_PINS_DEBUG_UART_RX_NAME "DEBUG_UART_RX"
/*!
 * @brief Direction */
#define INIT_PINS_DEBUG_UART_RX_DIRECTION kPIN_MUX_DirectionInput
/*!
 * @brief PORT peripheral base pointer */
#define INIT_PINS_DEBUG_UART_RX_PORT 0
/*!
 * @brief PORT pin number */
#define INIT_PINS_DEBUG_UART_RX_PIN 29U
/*!
 * @brief PORT pin mask */
#define INIT_PINS_DEBUG_UART_RX_PIN_MASK (1U << 29U)
/* @} */
/*! @name PWM0_A0 (number 11), J10[15]/P1_20-ADC1_8A-PWM0_A0
  @{ */
/* Routed pin properties */
#define INIT_PINS_PWM_A0_PERIPHERAL PWM0                       /*!<@brief Peripheral name */
#define INIT_PINS_PWM_A0_SIGNAL A                              /*!<@brief Signal name */
#define INIT_PINS_PWM_A0_CHANNEL 0                             /*!<@brief Signal channel */
#define INIT_PINS_PWM_A0_PIN_NAME PWM0_A0                      /*!<@brief Routed pin name */
#define INIT_PINS_PWM_A0_LABEL "J10[15]/P1_20-ADC1_8A-PWM0_A0" /*!<@brief Label */
#define INIT_PINS_PWM_A0_NAME "PWM_A0"                         /*!<@brief Identifier */
#define INIT_PINS_PWM_A0_DIRECTION kPIN_MUX_DirectionOutput    /*!<@brief Direction */
#define INIT_PINS_PWM_A0_PORT 1                                /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_PWM_A0_PIN 20U                               /*!<@brief PORT pin number */
#define INIT_PINS_PWM_A0_PIN_MASK (1U << 20U)                  /*!<@brief PORT pin mask */
                                                               /* @} */
/*! @name PWM0_A1 (number 50), J10[11]/P1_6-PWM0_A1
  @{ */
/* Routed pin properties */
#define INIT_PINS_PWM_A1_PERIPHERAL PWM0                    /*!<@brief Peripheral name */
#define INIT_PINS_PWM_A1_SIGNAL A                           /*!<@brief Signal name */
#define INIT_PINS_PWM_A1_CHANNEL 1                          /*!<@brief Signal channel */
#define INIT_PINS_PWM_A1_PIN_NAME PWM0_A1                   /*!<@brief Routed pin name */
#define INIT_PINS_PWM_A1_LABEL "J10[11]/P1_6-PWM0_A1"       /*!<@brief Label */
#define INIT_PINS_PWM_A1_NAME "PWM_A1"                      /*!<@brief Identifier */
#define INIT_PINS_PWM_A1_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
#define INIT_PINS_PWM_A1_PORT 1                             /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_PWM_A1_PIN 6U                             /*!<@brief PORT pin number */
#define INIT_PINS_PWM_A1_PIN_MASK (1U << 6U)                /*!<@brief PORT pin mask */
                                                            /* @} */
/*! @name PWM0_B0 (number 91), J10[13]/P1_17-PWM0_B0
  @{ */
/* Routed pin properties */
#define INIT_PINS_PWM_B0_PERIPHERAL PWM0                    /*!<@brief Peripheral name */
#define INIT_PINS_PWM_B0_SIGNAL B                           /*!<@brief Signal name */
#define INIT_PINS_PWM_B0_CHANNEL 0                          /*!<@brief Signal channel */
#define INIT_PINS_PWM_B0_PIN_NAME PWM0_B0                   /*!<@brief Routed pin name */
#define INIT_PINS_PWM_B0_LABEL "J10[13]/P1_17-PWM0_B0"      /*!<@brief Label */
#define INIT_PINS_PWM_B0_NAME "PWM_B0"                      /*!<@brief Identifier */
#define INIT_PINS_PWM_B0_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
#define INIT_PINS_PWM_B0_PORT 1                             /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_PWM_B0_PIN 17U                            /*!<@brief PORT pin number */
#define INIT_PINS_PWM_B0_PIN_MASK (1U << 17U)               /*!<@brief PORT pin mask */
                                                            /* @} */
/*! @name PWM0_B2 (number 75), J10[5]/P1_4-PWM0_B2
  @{ */
/* Routed pin properties */
#define INIT_PINS_PWM_B2_PERIPHERAL PWM0                    /*!<@brief Peripheral name */
#define INIT_PINS_PWM_B2_SIGNAL B                           /*!<@brief Signal name */
#define INIT_PINS_PWM_B2_CHANNEL 2                          /*!<@brief Signal channel */
#define INIT_PINS_PWM_B2_PIN_NAME PWM0_B2                   /*!<@brief Routed pin name */
#define INIT_PINS_PWM_B2_LABEL "J10[5]/P1_4-PWM0_B2"        /*!<@brief Label */
#define INIT_PINS_PWM_B2_NAME "PWM_B2"                      /*!<@brief Identifier */
#define INIT_PINS_PWM_B2_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
#define INIT_PINS_PWM_B2_PORT 1                             /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_PWM_B2_PIN 4U                             /*!<@brief PORT pin number */
#define INIT_PINS_PWM_B2_PIN_MASK (1U << 4U)                /*!<@brief PORT pin mask */
                                                            /* @} */
/*! @name PWM0_B1 (number 40), JP48[3]/J10[9]/P1_22-HSCMP1_IN1-DAC0_OUT-PWM0_B1_CAN0_RD
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define INIT_PINS_PWM_B1_PERIPHERAL PWM0
/*!
 * @brief Signal name */
#define INIT_PINS_PWM_B1_SIGNAL B
/*!
 * @brief Signal channel */
#define INIT_PINS_PWM_B1_CHANNEL 1
/*!
 * @brief Routed pin name */
#define INIT_PINS_PWM_B1_PIN_NAME PWM0_B1
/*!
 * @brief Label */
#define INIT_PINS_PWM_B1_LABEL "JP48[3]/J10[9]/P1_22-HSCMP1_IN1-DAC0_OUT-PWM0_B1_CAN0_RD"
/*!
 * @brief Identifier */
#define INIT_PINS_PWM_B1_NAME "PWM_B1"
/*!
 * @brief Direction */
#define INIT_PINS_PWM_B1_DIRECTION kPIN_MUX_DirectionOutput
/*!
 * @brief PORT peripheral base pointer */
#define INIT_PINS_PWM_B1_PORT 1
/*!
 * @brief PORT pin number */
#define INIT_PINS_PWM_B1_PIN 22U
/*!
 * @brief PORT pin mask */
#define INIT_PINS_PWM_B1_PIN_MASK (1U << 22U)
/* @} */
/*! @name PWM0_A2 (number 36), J8[1]/P1_8-FC0_CTS-PWM0_A2
  @{ */
/* Routed pin properties */
#define INIT_PINS_PWM_A2_PERIPHERAL PWM0                    /*!<@brief Peripheral name */
#define INIT_PINS_PWM_A2_SIGNAL A                           /*!<@brief Signal name */
#define INIT_PINS_PWM_A2_CHANNEL 2                          /*!<@brief Signal channel */
#define INIT_PINS_PWM_A2_PIN_NAME PWM0_A2                   /*!<@brief Routed pin name */
#define INIT_PINS_PWM_A2_LABEL "J8[1]/P1_8-FC0_CTS-PWM0_A2" /*!<@brief Label */
#define INIT_PINS_PWM_A2_NAME "PWM_A2"                      /*!<@brief Identifier */
#define INIT_PINS_PWM_A2_PORT 1                             /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_PWM_A2_PIN 8U                             /*!<@brief PORT pin number */
#define INIT_PINS_PWM_A2_PIN_MASK (1U << 8U)                /*!<@brief PORT pin mask */
                                                            /* @} */
/*! @name ADC0_1A (number 21), VOLT_DCB
  @{ */
/* Routed pin properties */
#define INIT_PINS_ADC_VDCB_PERIPHERAL ADC0           /*!<@brief Peripheral name */
#define INIT_PINS_ADC_VDCB_SIGNAL CH                 /*!<@brief Signal name */
#define INIT_PINS_ADC_VDCB_CHANNEL 1A                /*!<@brief Signal channel */
#define INIT_PINS_ADC_VDCB_PIN_NAME ADC0_1A          /*!<@brief Routed pin name */
#define INIT_PINS_ADC_VDCB_LABEL "VOLT_DCB"          /*!<@brief Label */
#define INIT_PINS_ADC_VDCB_NAME "ADC_VDCB"           /*!<@brief Identifier */
#define INIT_PINS_ADC_VDCB_PORT 0                    /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_ADC_VDCB_PIN 10U                   /*!<@brief PORT pin number */
#define INIT_PINS_ADC_VDCB_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                     /* @} */
/*! @name ADC0_3B (number 20), CUR_C
  @{ */
/* Routed pin properties */
#define INIT_PINS_ADC_CUR_C_PERIPHERAL ADC0           /*!<@brief Peripheral name */
#define INIT_PINS_ADC_CUR_C_SIGNAL CH                 /*!<@brief Signal name */
#define INIT_PINS_ADC_CUR_C_CHANNEL 3B                /*!<@brief Signal channel */
#define INIT_PINS_ADC_CUR_C_PIN_NAME ADC0_3B          /*!<@brief Routed pin name */
#define INIT_PINS_ADC_CUR_C_LABEL "CUR_C"             /*!<@brief Label */
#define INIT_PINS_ADC_CUR_C_NAME "ADC_CUR_C"          /*!<@brief Identifier */
#define INIT_PINS_ADC_CUR_C_PORT 0                    /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_ADC_CUR_C_PIN 16U                   /*!<@brief PORT pin number */
#define INIT_PINS_ADC_CUR_C_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */
/*! @name ADC0_8B (number 19), CUR_B
  @{ */
/* Routed pin properties */
#define INIT_PINS_ADC_CUR_B_PERIPHERAL ADC0           /*!<@brief Peripheral name */
#define INIT_PINS_ADC_CUR_B_SIGNAL CH                 /*!<@brief Signal name */
#define INIT_PINS_ADC_CUR_B_CHANNEL 8B                /*!<@brief Signal channel */
#define INIT_PINS_ADC_CUR_B_PIN_NAME ADC0_8B          /*!<@brief Routed pin name */
#define INIT_PINS_ADC_CUR_B_LABEL "CUR_B"             /*!<@brief Label */
#define INIT_PINS_ADC_CUR_B_NAME "ADC_CUR_B"          /*!<@brief Identifier */
#define INIT_PINS_ADC_CUR_B_PORT 0                    /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_ADC_CUR_B_PIN 23U                   /*!<@brief PORT pin number */
#define INIT_PINS_ADC_CUR_B_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                      /* @} */
/*! @name ADC0_3A (number 22), CUR_A
  @{ */
/* Routed pin properties */
#define INIT_PINS_ADC_CUR_A_PERIPHERAL ADC0           /*!<@brief Peripheral name */
#define INIT_PINS_ADC_CUR_A_SIGNAL CH                 /*!<@brief Signal name */
#define INIT_PINS_ADC_CUR_A_CHANNEL 3A                /*!<@brief Signal channel */
#define INIT_PINS_ADC_CUR_A_PIN_NAME ADC0_3A          /*!<@brief Routed pin name */
#define INIT_PINS_ADC_CUR_A_LABEL "CUR_A"             /*!<@brief Label */
#define INIT_PINS_ADC_CUR_A_NAME "ADC_CUR_A"          /*!<@brief Identifier */
#define INIT_PINS_ADC_CUR_A_PORT 0                    /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_ADC_CUR_A_PIN 15U                   /*!<@brief PORT pin number */
#define INIT_PINS_ADC_CUR_A_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                      /* @} */
/*! @name EXTTRIG_IN3 (number 70), J10[3]/U27[1]/P0_13-FC1_SDA-SCT0_GPI0-EXTTRIG_IN3
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define INIT_PINS_ENC0_PHA_PERIPHERAL ENC0
/*!
 * @brief Signal name */
#define INIT_PINS_ENC0_PHA_SIGNAL PHASE
/*!
 * @brief Signal channel */
#define INIT_PINS_ENC0_PHA_CHANNEL A
/*!
 * @brief Routed pin name */
#define INIT_PINS_ENC0_PHA_PIN_NAME EXTTRIG_IN3
/*!
 * @brief Label */
#define INIT_PINS_ENC0_PHA_LABEL "J10[3]/U27[1]/P0_13-FC1_SDA-SCT0_GPI0-EXTTRIG_IN3"
/*!
 * @brief Identifier */
#define INIT_PINS_ENC0_PHA_NAME "ENC0_PHA"
/*!
 * @brief PORT peripheral base pointer */
#define INIT_PINS_ENC0_PHA_PORT 0
/*!
 * @brief PORT pin number */
#define INIT_PINS_ENC0_PHA_PIN 13U
/*!
 * @brief PORT pin mask */
#define INIT_PINS_ENC0_PHA_PIN_MASK (1U << 13U)
/* @} */
/*! @name EXTTRIG_IN2 (number 71), J10[1]/U27[8]/P0_14-FC1_SCL-SCT0_GPI1-EXTTRIG_IN2
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define INIT_PINS_ENC0_PHB_PERIPHERAL ENC0
/*!
 * @brief Signal name */
#define INIT_PINS_ENC0_PHB_SIGNAL PHASE
/*!
 * @brief Signal channel */
#define INIT_PINS_ENC0_PHB_CHANNEL B
/*!
 * @brief Routed pin name */
#define INIT_PINS_ENC0_PHB_PIN_NAME EXTTRIG_IN2
/*!
 * @brief Label */
#define INIT_PINS_ENC0_PHB_LABEL "J10[1]/U27[8]/P0_14-FC1_SCL-SCT0_GPI1-EXTTRIG_IN2"
/*!
 * @brief Identifier */
#define INIT_PINS_ENC0_PHB_NAME "ENC0_PHB"
/*!
 * @brief PORT peripheral base pointer */
#define INIT_PINS_ENC0_PHB_PORT 0
/*!
 * @brief PORT pin number */
#define INIT_PINS_ENC0_PHB_PIN 14U
/*!
 * @brief PORT pin mask */
#define INIT_PINS_ENC0_PHB_PIN_MASK (1U << 14U)
/* @} */
/*! @name PIO1_28 (number 72), J122[16]/P1_28
  @{ */
/* Routed pin properties */
#define INIT_PINS_LED_RED_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define INIT_PINS_LED_RED_SIGNAL PIO1                        /*!<@brief Signal name */
#define INIT_PINS_LED_RED_CHANNEL 28                         /*!<@brief Signal channel */
#define INIT_PINS_LED_RED_PIN_NAME PIO1_28                   /*!<@brief Routed pin name */
#define INIT_PINS_LED_RED_LABEL "J122[16]/P1_28"             /*!<@brief Label */
#define INIT_PINS_LED_RED_NAME "LED_RED"                     /*!<@brief Identifier */
#define INIT_PINS_LED_RED_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */

/* Symbols to be used with GPIO driver */
#define INIT_PINS_LED_RED_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define INIT_PINS_LED_RED_GPIO_PIN 28U                       /*!<@brief GPIO pin number */
#define INIT_PINS_LED_RED_GPIO_PIN_MASK (1U << 28U)          /*!<@brief GPIO pin mask */
#define INIT_PINS_LED_RED_PORT 1                             /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_LED_RED_PIN 28U                            /*!<@brief PORT pin number */
#define INIT_PINS_LED_RED_PIN_MASK (1U << 28U)               /*!<@brief PORT pin mask */
                                                             /* @} */
/*! @name PIO0_22 (number 78), J12[8]/JP72[2]/P0_22
  @{ */
/* Routed pin properties */
#define INIT_PINS_LED_GREEN_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define INIT_PINS_LED_GREEN_SIGNAL PIO0                        /*!<@brief Signal name */
#define INIT_PINS_LED_GREEN_CHANNEL 22                         /*!<@brief Signal channel */
#define INIT_PINS_LED_GREEN_PIN_NAME PIO0_22                   /*!<@brief Routed pin name */
#define INIT_PINS_LED_GREEN_LABEL "J12[8]/JP72[2]/P0_22"       /*!<@brief Label */
#define INIT_PINS_LED_GREEN_NAME "LED_GREEN"                   /*!<@brief Identifier */
#define INIT_PINS_LED_GREEN_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */

/* Symbols to be used with GPIO driver */
#define INIT_PINS_LED_GREEN_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define INIT_PINS_LED_GREEN_GPIO_PIN 22U                       /*!<@brief GPIO pin number */
#define INIT_PINS_LED_GREEN_GPIO_PIN_MASK (1U << 22U)          /*!<@brief GPIO pin mask */
#define INIT_PINS_LED_GREEN_PORT 0                             /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_LED_GREEN_PIN 22U                            /*!<@brief PORT pin number */
#define INIT_PINS_LED_GREEN_PIN_MASK (1U << 22U)               /*!<@brief PORT pin mask */
                                                               /* @} */
/*! @name PIO0_17 (number 41), JP73[2]/J8[2]/P0_17
  @{ */
/* Routed pin properties */
#define INIT_PINS_SW3_PERIPHERAL PINT             /*!<@brief Peripheral name */
#define INIT_PINS_SW3_SIGNAL PINT                 /*!<@brief Signal name */
#define INIT_PINS_SW3_CHANNEL 0                   /*!<@brief Signal channel */
#define INIT_PINS_SW3_PIN_NAME PIO0_17            /*!<@brief Routed pin name */
#define INIT_PINS_SW3_LABEL "JP73[2]/J8[2]/P0_17" /*!<@brief Label */
#define INIT_PINS_SW3_NAME "SW3"                  /*!<@brief Identifier */
#define INIT_PINS_SW3_PORT 0                      /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_SW3_PIN 17U                     /*!<@brief PORT pin number */
#define INIT_PINS_SW3_PIN_MASK (1U << 17U)        /*!<@brief PORT pin mask */
                                                  /* @} */
/*! @name ADC0_8A (number 23), P0_31-ADC0_8A
  @{ */
/* Routed pin properties */
#define INIT_PINS_ADC0_8A_PERIPHERAL ADC0           /*!<@brief Peripheral name */
#define INIT_PINS_ADC0_8A_SIGNAL CH                 /*!<@brief Signal name */
#define INIT_PINS_ADC0_8A_CHANNEL 8A                /*!<@brief Signal channel */
#define INIT_PINS_ADC0_8A_PIN_NAME ADC0_8A          /*!<@brief Routed pin name */
#define INIT_PINS_ADC0_8A_LABEL "P0_31-ADC0_8A"     /*!<@brief Label */
#define INIT_PINS_ADC0_8A_NAME "ADC0_8A"            /*!<@brief Identifier */
#define INIT_PINS_ADC0_8A_PORT 0                    /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_ADC0_8A_PIN 31U                   /*!<@brief PORT pin number */
#define INIT_PINS_ADC0_8A_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                    /* @} */
/*! @name HSCMP0_IN3 (number 35), P1_5-HSCMP0_IN3
  @{ */
/* Routed pin properties */
#define INIT_PINS_HSCMP0_IN3_PERIPHERAL HSCMP0        /*!<@brief Peripheral name */
#define INIT_PINS_HSCMP0_IN3_SIGNAL IN                /*!<@brief Signal name */
#define INIT_PINS_HSCMP0_IN3_CHANNEL 3                /*!<@brief Signal channel */
#define INIT_PINS_HSCMP0_IN3_PIN_NAME HSCMP0_IN3      /*!<@brief Routed pin name */
#define INIT_PINS_HSCMP0_IN3_LABEL "P1_5-HSCMP0_IN3"  /*!<@brief Label */
#define INIT_PINS_HSCMP0_IN3_NAME "HSCMP0_IN3"        /*!<@brief Identifier */
#define INIT_PINS_HSCMP0_IN3_PORT 1                   /*!<@brief PORT peripheral base pointer */
#define INIT_PINS_HSCMP0_IN3_PIN 5U                   /*!<@brief PORT pin number */
#define INIT_PINS_HSCMP0_IN3_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                      /* @} */
/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_Pins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
